name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

cache-mode: none

jobs:
  deploy:
    uses: yearn/yearn-gha/.github/workflows/cloudflare-deploy.yml@22362daf9934a759c1c9c258388111271e649faa
    with:
      project: yearn-artifacts
      identity-id: ${{ vars.DOPPLER_PRODUCTION_IDENTITY_ID }}
